name: Decks  
on: [push]
jobs:
  deploy_source:
    name: Deploy API Using Lambda
    strategy:
      matrix:
        node-version: [12.x]
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and build
        run: |
          npm ci
          npm run build --if-present
        env:
          CI: true

      - name: /decks get lambda deploy zip
        uses: postman-open-technologies/decks@main
        with:
            args: zip -qq -r m-s-decks-g.zip decks/get/index.js node_modules
      - name: deck get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-decks-g
            zip_file: m-s-decks-g.zip
      - name: /decks post lambda deploy zip
        uses: postman-open-technologies/decks@main
        with:
            args: zip -qq -r m-s-decks-po.zip decks/post/index.js node_modules
      - name: deck get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-decks-po
            zip_file: m-s-decks-po.zip
      - name: /decks/{deck_id} get lambda deploy zip
        uses: postman-open-technologies/decks@main
        with:
            args: zip -qq -r m-s-decks-deck-g.zip decks/deck_id/get/index.js node_modules
      - name: deck get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-decks-deck-g
            zip_file: m-s-decks-deck-g.zip
      - name: /decks/{deck_id} put lambda deploy zip
        uses: postman-open-technologies/decks@main
        with:
            args: zip -qq -r m-s-decks-deck-pu.zip decks/deck_id/put/index.js node_modules
      - name: deck get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-decks-deck-pu
            zip_file: m-s-decks-deck-pu.zip
      - name: /decks/{deck_id} delete lambda deploy zip
        uses: postman-open-technologies/decks@main
        with:
            args: zip -qq -r m-s-decks-deck-d.zip decks/deck_id/delete/index.js node_modules
      - name: deck get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-decks-deck-d
            zip_file: m-s-decks-deck-d.zip          
      - name: /decks/{deck_id}/tags get lambda deploy zip
        uses: postman-open-technologies/decks@main
        with:
            args: zip -qq -r m-s-decks-deck-tags-g.zip decks/deck_id/tags/get/index.js node_modules
      - name: decks get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-decks-deck-tags-g
            zip_file: m-s-decks-deck-tags-g.zip
      - name: /decks/{deck_id}/tags post lambda deploy zip
        uses: postman-open-technologies/decks@main
        with:
            args: zip -qq -r m-s-decks-deck-tags-po.zip decks/deck_id/tags/post/index.js node_modules
      - name: decks get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-decks-deck-tags-po
            zip_file: m-s-decks-deck-tags-po.zip
      - name: /decks/{deck_id}/tags/{tag_id} delete lambda deploy zip
        uses: postman-open-technologies/decks@main
        with:
            args: zip -qq -r m-s-decks-deck-tags-tag-d.zip decks/deck_id/tags/tag_id/delete/index.js node_modules
      - name: decks get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-decks-deck-tags-tag-d
            zip_file: m-s-decks-deck-tags-tag-d.zip            